apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-k8s-demo # Phải khớp tên Deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50 # Scale khi CPU trung bình > 50% request